import { env } from "../config/env.js";
import { AppSettings } from "../models/AppSettings.js";
import { Auction } from "../models/Auction.js";
import { Bid } from "../models/Bid.js";
import { Listing } from "../models/Listing.js";
import { Order } from "../models/Order.js";
import { Report } from "../models/Report.js";
import { Thread } from "../models/Thread.js";
import { Transaction } from "../models/Transaction.js";
import { User } from "../models/User.js";
import { Watchlist } from "../models/Watchlist.js";
import { hashPassword } from "../utils/security.js";

function daysAgo(value) {
  const date = new Date();
  date.setDate(date.getDate() - value);
  return date;
}

async function createOrUpdateAdmin() {
  const password = await hashPassword(env.adminPassword);

  await User.findOneAndUpdate(
    { email: env.adminEmail.toLowerCase() },
    {
      $set: {
        name: "Super Admin",
        email: env.adminEmail.toLowerCase(),
        password,
        role: "Admin",
        publicRoleLabel: "Platform owner",
        status: "Active",
        country: "Bangladesh",
        location: "Dhaka, Bangladesh",
        contact: "Admin Console",
        preferences: {
          twoFactorMode: "Enabled",
          sessionTimeout: "30 minutes",
          auditEmail: env.adminEmail.toLowerCase(),
        },
        stats: {
          casesHandled: 214,
          criticalActions: 39,
          adminSessions: 128,
          riskReviews: 47,
        },
      },
    },
    { upsert: true, new: true },
  );
}

async function seedMarketplace() {
  const publicUserCount = await User.countDocuments({
    role: { $in: ["Seller", "Bidder"] },
  });

  if (publicUserCount > 0) {
    return;
  }

  const samplePassword = await hashPassword("Password@123");

  const users = await User.insertMany([
    {
      name: "Prime Auto Gallery",
      email: "seller@auctionarc.com",
      password: samplePassword,
      role: "Seller",
      publicRoleLabel: "Verified seller",
      status: "Active",
      birthdate: new Date("1990-04-12"),
      country: "Bangladesh",
      location: "Dhaka, Bangladesh",
      contact: "+8801711000100",
      nid: "NID-SLR-1001",
      verification: {
        isAdultVerified: true,
        isIdentityVerified: true,
        isWalletVerified: true,
      },
      wallet: {
        availableBalance: 24800,
        heldBalance: 7000,
        pendingPayout: 16800,
        platformFees: 2300,
        walletLabel: "Seller wallet",
      },
      preferences: {
        emailAlerts: "Enabled",
        payoutAlerts: "Enabled",
        messageAlerts: "Instant",
        defaultAuctionDuration: "7 days",
        defaultShipping: "Standard insured shipping",
        reserveReminder: "Enabled",
        responseWindow: "Within 1 hour",
        featuredAppearance: "Enabled",
      },
      stats: {
        sellerRating: 4.9,
        completedSales: 84,
        buyerResponseMinutes: 18,
      },
      createdAt: daysAgo(8),
      updatedAt: daysAgo(1),
    },
    {
      name: "Heritage Vault",
      email: "heritage@auctionarc.com",
      password: samplePassword,
      role: "Seller",
      publicRoleLabel: "Trusted seller",
      status: "Active",
      birthdate: new Date("1988-01-18"),
      country: "Bangladesh",
      location: "Dhaka, Bangladesh",
      contact: "+8801711000101",
      nid: "NID-SLR-1002",
      verification: {
        isAdultVerified: true,
        isIdentityVerified: true,
        isWalletVerified: true,
      },
      wallet: {
        availableBalance: 19300,
        heldBalance: 1800,
        pendingPayout: 8900,
        platformFees: 1800,
        walletLabel: "Heritage settlement wallet",
      },
      stats: {
        sellerRating: 4.8,
        completedSales: 65,
        buyerResponseMinutes: 22,
      },
      createdAt: daysAgo(11),
      updatedAt: daysAgo(1),
    },
    {
      name: "M. Rahman",
      email: "m.rahman@auctionarc.com",
      password: samplePassword,
      role: "Seller",
      publicRoleLabel: "Pending seller",
      status: "Pending verification",
      birthdate: new Date("1997-06-03"),
      country: "Bangladesh",
      location: "Dhaka, Bangladesh",
      contact: "+8801711000001",
      nid: "NID-SLR-1003",
      verification: {
        isAdultVerified: true,
        isIdentityVerified: false,
        isWalletVerified: false,
      },
      wallet: {
        availableBalance: 300,
        heldBalance: 0,
        pendingPayout: 0,
        platformFees: 0,
        walletLabel: "Starter seller wallet",
      },
      createdAt: daysAgo(6),
      updatedAt: daysAgo(2),
    },
    {
      name: "Avery Stone",
      email: "bidder@auctionarc.com",
      password: samplePassword,
      role: "Bidder",
      publicRoleLabel: "Active bidder",
      status: "Active",
      birthdate: new Date("1995-09-21"),
      country: "United States",
      location: "New York, United States",
      contact: "+12025550191",
      nid: "ID-BDR-2001",
      verification: {
        isAdultVerified: true,
        isIdentityVerified: true,
        isWalletVerified: true,
      },
      wallet: {
        availableBalance: 12600,
        heldBalance: 6400,
        pendingPayout: 0,
        platformFees: 0,
        walletLabel: "Bidder wallet",
      },
      preferences: {
        outbidAlerts: "Instant",
        endingAlerts: "Enabled",
        supportAlerts: "Enabled",
        currency: "USD",
        walletMode: "Manual",
        categoryFocus: "Vehicles, Collectibles",
      },
      stats: {
        winningRate: 28,
        watchlistGrowth: 27,
        averageBidResponseMinutes: 11,
      },
      createdAt: daysAgo(12),
      updatedAt: daysAgo(1),
    },
    {
      name: "Ethan Brooks",
      email: "ethan@auctionarc.com",
      password: samplePassword,
      role: "Bidder",
      publicRoleLabel: "Bidder",
      status: "Suspended",
      birthdate: new Date("1992-12-11"),
      country: "United Kingdom",
      location: "London, United Kingdom",
      contact: "+447911123456",
      nid: "ID-BDR-2002",
      verification: {
        isAdultVerified: true,
        isIdentityVerified: true,
        isWalletVerified: true,
      },
      wallet: {
        availableBalance: 9200,
        heldBalance: 1000,
        pendingPayout: 0,
        platformFees: 0,
        walletLabel: "UK bidder wallet",
      },
      createdAt: daysAgo(15),
      updatedAt: daysAgo(3),
    },
    {
      name: "Lima Estates",
      email: "lima@auctionarc.com",
      password: samplePassword,
      role: "Bidder",
      publicRoleLabel: "High intent bidder",
      status: "Active",
      birthdate: new Date("1989-08-16"),
      country: "Bangladesh",
      location: "Dhaka, Bangladesh",
      contact: "+8801711000300",
      nid: "ID-BDR-2003",
      verification: {
        isAdultVerified: true,
        isIdentityVerified: true,
        isWalletVerified: true,
      },
      wallet: {
        availableBalance: 98400,
        heldBalance: 7000,
        pendingPayout: 0,
        platformFees: 0,
        walletLabel: "Enterprise bidder wallet",
      },
      createdAt: daysAgo(9),
      updatedAt: daysAgo(1),
    },
  ]);

  const byEmail = Object.fromEntries(users.map((user) => [user.email, user]));

  const listings = await Listing.insertMany([
    {
      code: "SL-101",
      seller: byEmail["seller@auctionarc.com"]._id,
      title: "Toyota Land Cruiser",
      category: "Vehicles",
      status: "Live",
      reserveStatus: "Met",
      price: 41000,
      reservePrice: 39000,
      currentBid: 41000,
      bidCount: 14,
      watcherCount: 49,
      viewCount: 220,
      notes: ["Seller verification complete, pending image quality review."],
      createdAt: daysAgo(7),
      updatedAt: daysAgo(1),
    },
    {
      code: "SL-102",
      seller: byEmail["heritage@auctionarc.com"]._id,
      title: "Vintage Rolex 1968",
      category: "Collectibles",
      status: "Featured",
      reserveStatus: "Met",
      price: 18400,
      reservePrice: 17000,
      currentBid: 18400,
      bidCount: 93,
      watcherCount: 112,
      viewCount: 380,
      notes: ["Authenticity proof uploaded and reviewed."],
      createdAt: daysAgo(10),
      updatedAt: daysAgo(1),
    },
    {
      code: "SL-103",
      seller: byEmail["seller@auctionarc.com"]._id,
      title: "Industrial lathe unit",
      category: "Industrial",
      status: "Pending review",
      reserveStatus: "Pending",
      price: 12250,
      reservePrice: 13000,
      currentBid: 12250,
      bidCount: 22,
      watcherCount: 33,
      viewCount: 140,
      notes: ["Reserve price set 8% above recent auction benchmark."],
      createdAt: daysAgo(5),
      updatedAt: daysAgo(2),
    },
    {
      code: "SL-104",
      seller: byEmail["seller@auctionarc.com"]._id,
      title: "MacBook bundle",
      category: "Electronics",
      status: "Draft",
      reserveStatus: "Not set",
      price: 5500,
      reservePrice: 0,
      currentBid: 0,
      bidCount: 0,
      watcherCount: 8,
      viewCount: 21,
      createdAt: daysAgo(2),
      updatedAt: daysAgo(1),
    },
    {
      code: "PRD-994",
      seller: byEmail["m.rahman@auctionarc.com"]._id,
      title: "Smartphone bundle",
      category: "Electronics",
      status: "Rejected",
      reserveStatus: "Held",
      price: 2100,
      reservePrice: 2300,
      currentBid: 0,
      bidCount: 0,
      watcherCount: 3,
      viewCount: 15,
      notes: ["Rejected for incomplete provenance details."],
      createdAt: daysAgo(4),
      updatedAt: daysAgo(2),
    },
    {
      code: "PRD-991",
      seller: byEmail["heritage@auctionarc.com"]._id,
      title: "Vintage Rolex 1968",
      category: "Collectibles",
      status: "Live",
      reserveStatus: "Met",
      price: 18400,
      reservePrice: 17000,
      currentBid: 18400,
      bidCount: 93,
      watcherCount: 112,
      viewCount: 380,
      createdAt: daysAgo(10),
      updatedAt: daysAgo(1),
    },
    {
      code: "PRD-992",
      seller: byEmail["seller@auctionarc.com"]._id,
      title: "Toyota Land Cruiser",
      category: "Vehicles",
      status: "Pending approval",
      reserveStatus: "Met",
      price: 41000,
      reservePrice: 39000,
      currentBid: 41000,
      bidCount: 14,
      watcherCount: 49,
      viewCount: 220,
      createdAt: daysAgo(7),
      updatedAt: daysAgo(1),
    },
    {
      code: "PRD-993",
      seller: byEmail["seller@auctionarc.com"]._id,
      title: "Industrial lathe unit",
      category: "Industrial",
      status: "Featured",
      reserveStatus: "Pending",
      price: 12250,
      reservePrice: 13000,
      currentBid: 12250,
      bidCount: 22,
      watcherCount: 33,
      viewCount: 140,
      createdAt: daysAgo(5),
      updatedAt: daysAgo(2),
    },
  ]);

  const byCode = Object.fromEntries(listings.map((listing) => [listing.code, listing]));

  const auctions = await Auction.insertMany([
    {
      code: "SA-21",
      listing: byCode["SL-101"]._id,
      seller: byCode["SL-101"].seller,
      title: "Luxury sedan auction",
      status: "Extended",
      reserveStatus: "Near",
      currentBid: 27100,
      watcherCount: 49,
      bidCount: 63,
      startAt: daysAgo(1),
      endAt: new Date(Date.now() + 18 * 60 * 1000),
      category: "Vehicles",
      createdAt: daysAgo(6),
      updatedAt: daysAgo(1),
    },
    {
      code: "SA-22",
      listing: byCode["SL-102"]._id,
      seller: byCode["SL-102"].seller,
      title: "Vintage Rolex 1968",
      status: "Live",
      reserveStatus: "Met",
      currentBid: 18400,
      watcherCount: 112,
      bidCount: 93,
      startAt: daysAgo(2),
      endAt: new Date(Date.now() + 32 * 60 * 1000),
      featured: true,
      category: "Collectibles",
      createdAt: daysAgo(10),
      updatedAt: daysAgo(1),
    },
    {
      code: "SA-23",
      listing: byCode["SL-103"]._id,
      seller: byCode["SL-103"].seller,
      title: "Dhaka Condo Lot",
      status: "Scheduled",
      reserveStatus: "Pending",
      currentBid: 0,
      watcherCount: 28,
      bidCount: 0,
      startAt: new Date(Date.now() + 6 * 60 * 60 * 1000),
      endAt: new Date(Date.now() + 30 * 60 * 60 * 1000),
      category: "Property",
      createdAt: daysAgo(2),
      updatedAt: daysAgo(1),
    },
    {
      code: "AUC-401",
      listing: byCode["SL-103"]._id,
      seller: byCode["SL-103"].seller,
      title: "Dhaka Condo Lot",
      status: "Live",
      reserveStatus: "Met",
      currentBid: 93000,
      watcherCount: 57,
      bidCount: 57,
      startAt: daysAgo(1),
      endAt: new Date(Date.now() + 12 * 60 * 1000),
      category: "Property",
      createdAt: daysAgo(5),
      updatedAt: daysAgo(1),
    },
    {
      code: "AUC-402",
      listing: byCode["SL-101"]._id,
      seller: byCode["SL-101"].seller,
      title: "Luxury Sedan Auction",
      status: "Extended",
      reserveStatus: "Near",
      currentBid: 27100,
      watcherCount: 63,
      bidCount: 63,
      startAt: daysAgo(1),
      endAt: new Date(Date.now() + 18 * 60 * 1000),
      category: "Vehicles",
      createdAt: daysAgo(6),
      updatedAt: daysAgo(1),
    },
    {
      code: "AUC-403",
      listing: byCode["SL-102"]._id,
      seller: byCode["SL-102"].seller,
      title: "Antique Coin Set",
      status: "Scheduled",
      reserveStatus: "Pending",
      currentBid: 0,
      watcherCount: 13,
      bidCount: 0,
      startAt: new Date(Date.now() + 4 * 60 * 60 * 1000),
      endAt: new Date(Date.now() + 24 * 60 * 60 * 1000),
      category: "Collectibles",
      createdAt: daysAgo(3),
      updatedAt: daysAgo(1),
    },
    {
      code: "AUC-404",
      listing: byCode["PRD-994"]._id,
      seller: byCode["PRD-994"].seller,
      title: "Server Rack Inventory",
      status: "Under review",
      reserveStatus: "Held",
      currentBid: 12250,
      watcherCount: 11,
      bidCount: 11,
      startAt: daysAgo(1),
      endAt: new Date(Date.now() + 90 * 60 * 1000),
      category: "Industrial",
      createdAt: daysAgo(4),
      updatedAt: daysAgo(1),
    },
    {
      code: "BD-11",
      listing: byCode["SL-101"]._id,
      seller: byCode["SL-101"].seller,
      title: "Classic motorbike",
      status: "Scheduled",
      reserveStatus: "Pending",
      currentBid: 8100,
      watcherCount: 42,
      bidCount: 3,
      startAt: new Date(Date.now() + 8 * 60 * 60 * 1000),
      endAt: new Date(Date.now() + 32 * 60 * 60 * 1000),
      category: "Vehicles",
      createdAt: daysAgo(1),
      updatedAt: daysAgo(1),
    },
    {
      code: "BD-12",
      listing: byCode["SL-102"]._id,
      seller: byCode["SL-102"].seller,
      title: "Luxury watch set",
      status: "Live",
      reserveStatus: "Met",
      currentBid: 12900,
      watcherCount: 86,
      bidCount: 20,
      startAt: daysAgo(1),
      endAt: new Date(Date.now() + 4 * 60 * 60 * 1000),
      category: "Collectibles",
      createdAt: daysAgo(2),
      updatedAt: daysAgo(1),
    },
    {
      code: "BD-13",
      listing: byCode["SL-103"]._id,
      seller: byCode["SL-103"].seller,
      title: "Commercial generator",
      status: "Live",
      reserveStatus: "Near",
      currentBid: 15400,
      watcherCount: 51,
      bidCount: 9,
      startAt: daysAgo(1),
      endAt: new Date(Date.now() + 9 * 60 * 60 * 1000),
      category: "Industrial",
      createdAt: daysAgo(2),
      updatedAt: daysAgo(1),
    },
  ]);

  const auctionByCode = Object.fromEntries(auctions.map((auction) => [auction.code, auction]));

  await Bid.insertMany([
    {
      code: "BB-401",
      auction: auctionByCode["AUC-402"]._id,
      listing: byCode["SL-101"]._id,
      bidder: byEmail["bidder@auctionarc.com"]._id,
      amount: 27100,
      status: "Outbid",
      signal: "Normal",
      createdAt: daysAgo(1),
      updatedAt: daysAgo(1),
    },
    {
      code: "BB-402",
      auction: auctionByCode["SA-22"]._id,
      listing: byCode["SL-102"]._id,
      bidder: byEmail["bidder@auctionarc.com"]._id,
      amount: 18400,
      status: "Top bid",
      signal: "High intent",
      createdAt: daysAgo(1),
      updatedAt: daysAgo(1),
    },
    {
      code: "BB-403",
      auction: auctionByCode["AUC-404"]._id,
      listing: byCode["SL-103"]._id,
      bidder: byEmail["bidder@auctionarc.com"]._id,
      amount: 12250,
      status: "Pending check",
      signal: "Duplicate IP",
      createdAt: daysAgo(1),
      updatedAt: daysAgo(1),
    },
    {
      code: "BID-7102",
      auction: auctionByCode["AUC-402"]._id,
      listing: byCode["SL-101"]._id,
      bidder: byEmail["ethan@auctionarc.com"]._id,
      amount: 27100,
      status: "Held",
      signal: "Velocity spike",
      createdAt: daysAgo(1),
      updatedAt: daysAgo(1),
    },
    {
      code: "BID-7103",
      auction: auctionByCode["AUC-401"]._id,
      listing: byCode["SL-103"]._id,
      bidder: byEmail["lima@auctionarc.com"]._id,
      amount: 93000,
      status: "Valid",
      signal: "High intent",
      createdAt: daysAgo(1),
      updatedAt: daysAgo(1),
    },
    {
      code: "BID-7104",
      auction: auctionByCode["AUC-404"]._id,
      listing: byCode["SL-103"]._id,
      bidder: byEmail["lima@auctionarc.com"]._id,
      amount: 12250,
      status: "Review",
      signal: "Duplicate IP",
      createdAt: daysAgo(1),
      updatedAt: daysAgo(1),
    },
    {
      code: "BID-7101",
      auction: auctionByCode["SA-22"]._id,
      listing: byCode["SL-102"]._id,
      bidder: byEmail["bidder@auctionarc.com"]._id,
      amount: 18400,
      status: "Valid",
      signal: "Normal",
      createdAt: daysAgo(1),
      updatedAt: daysAgo(1),
    },
  ]);

  await Watchlist.insertMany([
    { user: byEmail["bidder@auctionarc.com"]._id, auction: auctionByCode["SA-22"]._id, createdAt: daysAgo(2), updatedAt: daysAgo(2) },
    { user: byEmail["bidder@auctionarc.com"]._id, auction: auctionByCode["AUC-402"]._id, createdAt: daysAgo(2), updatedAt: daysAgo(2) },
    { user: byEmail["bidder@auctionarc.com"]._id, auction: auctionByCode["SA-23"]._id, createdAt: daysAgo(1), updatedAt: daysAgo(1) },
  ]);

  await Order.insertMany([
    {
      code: "SO-501",
      item: "Classic camera bundle",
      seller: byEmail["seller@auctionarc.com"]._id,
      bidder: byEmail["bidder@auctionarc.com"]._id,
      listing: byCode["SL-101"]._id,
      amount: 4200,
      status: "Awaiting payout",
      escrowAmount: 0,
      createdAt: daysAgo(12),
      updatedAt: daysAgo(1),
    },
    {
      code: "SO-502",
      item: "Industrial lathe accessory set",
      seller: byEmail["seller@auctionarc.com"]._id,
      bidder: byEmail["lima@auctionarc.com"]._id,
      listing: byCode["SL-103"]._id,
      amount: 1850,
      status: "Completed",
      escrowAmount: 0,
      createdAt: daysAgo(9),
      updatedAt: daysAgo(2),
    },
    {
      code: "SO-503",
      item: "Luxury sedan deposit",
      seller: byEmail["seller@auctionarc.com"]._id,
      bidder: byEmail["lima@auctionarc.com"]._id,
      listing: byCode["SL-101"]._id,
      amount: 7000,
      status: "In escrow",
      escrowAmount: 7000,
      createdAt: daysAgo(3),
      updatedAt: daysAgo(1),
    },
    {
      code: "BWN-91",
      item: "Camera collector set",
      seller: byEmail["heritage@auctionarc.com"]._id,
      bidder: byEmail["bidder@auctionarc.com"]._id,
      listing: byCode["SL-102"]._id,
      amount: 4200,
      status: "Awaiting shipment",
      escrowAmount: 0,
      createdAt: daysAgo(6),
      updatedAt: daysAgo(1),
    },
    {
      code: "BWN-92",
      item: "Office furniture lot",
      seller: byEmail["seller@auctionarc.com"]._id,
      bidder: byEmail["bidder@auctionarc.com"]._id,
      listing: byCode["SL-104"]._id,
      amount: 2880,
      status: "Paid",
      escrowAmount: 0,
      createdAt: daysAgo(4),
      updatedAt: daysAgo(1),
    },
    {
      code: "BWN-93",
      item: "Industrial spare kit",
      seller: byEmail["heritage@auctionarc.com"]._id,
      bidder: byEmail["bidder@auctionarc.com"]._id,
      listing: byCode["SL-103"]._id,
      amount: 1050,
      status: "Delivered",
      escrowAmount: 0,
      createdAt: daysAgo(14),
      updatedAt: daysAgo(3),
    },
  ]);

  await Thread.insertMany([
    {
      code: "MSG-101",
      subject: "Shipping timeline for camera set",
      priority: "Normal",
      status: "Open",
      participants: [
        { user: byEmail["bidder@auctionarc.com"]._id, roleLabel: "Buyer", name: "Avery Stone" },
        { user: byEmail["seller@auctionarc.com"]._id, roleLabel: "Seller", name: "Prime Auto Gallery" },
      ],
      messages: [
        { senderName: "Buyer", senderRole: "Bidder", body: "Could you confirm the packaging and shipping timeline?", sentAt: daysAgo(2) },
        { senderName: "Seller", senderRole: "Seller", body: "Yes, dispatch is scheduled within two business days with insured delivery.", sentAt: daysAgo(1) },
      ],
      createdAt: daysAgo(2),
      updatedAt: daysAgo(1),
    },
    {
      code: "MSG-102",
      subject: "Wallet hold clarification",
      priority: "High",
      status: "Support active",
      participants: [{ user: byEmail["bidder@auctionarc.com"]._id, roleLabel: "Buyer", name: "Avery Stone" }],
      messages: [
        { senderName: "Buyer", senderRole: "Bidder", body: "Why is my balance still on hold after bidding?", sentAt: daysAgo(1) },
        { senderName: "Support", senderRole: "Support", body: "The hold remains until the auction state is finalized or your bid is released.", sentAt: new Date(Date.now() - 9 * 60 * 1000) },
      ],
      createdAt: daysAgo(1),
      updatedAt: new Date(Date.now() - 9 * 60 * 1000),
    },
    {
      code: "CHT-301",
      subject: "Payment delay after winning bid",
      priority: "High",
      status: "Escalated",
      participants: [
        { user: byEmail["bidder@auctionarc.com"]._id, roleLabel: "Bidder", name: "Avery Stone" },
        { user: byEmail["seller@auctionarc.com"]._id, roleLabel: "Seller", name: "Prime Auto Gallery" },
      ],
      messages: [
        { senderName: "Bidder", senderRole: "Bidder", body: "My wallet was charged but the seller still shows unpaid.", sentAt: daysAgo(1) },
        { senderName: "Support", senderRole: "Support", body: "We are checking settlement state and escrow release logs.", sentAt: daysAgo(1) },
        { senderName: "Admin note", senderRole: "Admin", body: "Mark finance review if payout remains pending after next sync window.", sentAt: daysAgo(1) },
      ],
      createdAt: daysAgo(1),
      updatedAt: daysAgo(1),
    },
    {
      code: "CHT-302",
      subject: "Listing authenticity complaint",
      priority: "Medium",
      status: "Open",
      participants: [
        { user: byEmail["bidder@auctionarc.com"]._id, roleLabel: "Bidder", name: "Avery Stone" },
        { user: byEmail["heritage@auctionarc.com"]._id, roleLabel: "Moderation", name: "Heritage Vault" },
      ],
      messages: [
        { senderName: "Bidder", senderRole: "Bidder", body: "I need authenticity proof before I continue bidding.", sentAt: daysAgo(2) },
        { senderName: "Moderation", senderRole: "Admin", body: "Seller has been asked to upload provenance documents.", sentAt: daysAgo(1) },
      ],
      createdAt: daysAgo(2),
      updatedAt: daysAgo(1),
    },
  ]);

  await Transaction.insertMany([
    { code: "TXN-8801", user: byEmail["bidder@auctionarc.com"]._id, type: "Wallet debit", status: "Completed", amount: 2400, channel: "Wallet", createdAt: daysAgo(3), updatedAt: daysAgo(3) },
    { code: "TXN-8802", user: byEmail["seller@auctionarc.com"]._id, type: "Seller payout", status: "Pending", amount: 18900, channel: "Bank transfer", createdAt: daysAgo(2), updatedAt: daysAgo(2) },
    { code: "TXN-8803", user: byEmail["m.rahman@auctionarc.com"]._id, type: "Registration fee", status: "Completed", amount: 25, channel: "Card", createdAt: daysAgo(6), updatedAt: daysAgo(6) },
    { code: "TXN-8804", user: byEmail["heritage@auctionarc.com"]._id, type: "Refund", status: "Review", amount: 480, channel: "Escrow", createdAt: daysAgo(1), updatedAt: daysAgo(1) },
  ]);

  await Report.insertMany([
    { code: "RPT-501", type: "Fraud", target: "User USR-1023", severity: "High", status: "Investigating", owner: "Super Admin", createdAt: daysAgo(2), updatedAt: daysAgo(1) },
    { code: "RPT-502", type: "Listing complaint", target: "Product PRD-994", severity: "Medium", status: "Queued", owner: "Moderation", createdAt: daysAgo(4), updatedAt: daysAgo(2) },
    { code: "RPT-503", type: "Bid dispute", target: "Auction AUC-402", severity: "High", status: "Escalated", owner: "Support", createdAt: daysAgo(1), updatedAt: daysAgo(1) },
    { code: "RPT-504", type: "Abuse report", target: "Chat CHT-302", severity: "Low", status: "Resolved", owner: "Support", createdAt: daysAgo(8), updatedAt: daysAgo(3) },
  ]);

  await AppSettings.findOneAndUpdate(
    { key: "marketplace-settings" },
    {
      key: "marketplace-settings",
      sections: [
        {
          title: "Marketplace structure",
          description: "Control categories, subcategories, and homepage merchandising rules.",
          items: ["Category manager", "Featured listing slots", "Homepage banner rotation"],
        },
        {
          title: "Auction rules",
          description: "Set durations, reserve logic, extension behavior, and review states.",
          items: ["Default auction duration", "Reserve threshold policy", "Auto-extension window"],
        },
        {
          title: "Payments and wallets",
          description: "Prepare the control surface for wallet providers, payouts, and escrow.",
          items: ["Wallet provider config", "Commission rates", "Payout release rules"],
        },
        {
          title: "Notifications and support",
          description: "Manage templates, SLA targets, canned responses, and support routing.",
          items: ["Email/SMS templates", "Dispute routing", "Support escalation policy"],
        },
      ],
    },
    { upsert: true, new: true },
  );
}

export async function bootstrapDatabase() {
  await createOrUpdateAdmin();

  if (env.seedOnBoot) {
    await seedMarketplace();
  }
}
